name: üß™ Test PR from fork

on:
  pull_request_target:
  workflow_call:
    secrets:
      SMTP_PWD:
        required: true
      SMTP_HOST:
        required: true
      SMTP_USER:
        required: true
      SESSION_SECRET:
        required: true
      SUPABASE_ANON_PUBLIC:
        required: true
      SUPABASE_SERVICE_ROLE:
        required: true
      SUPABASE_URL:
        required: true
      SERVER_URL:
        required: true
      DATABASE_URL:
        required: true
      DIRECT_URL:
        required: true
      SEND_ONBOARDING_EMAIL:
        required: true
      ENABLE_PREMIUM_FEATURES:
        required: true

jobs:
  authorize:
    environment: ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || '' }}

    runs-on: ubuntu-latest
    steps:
      - run: echo ‚úì

  lint:
    needs: authorize
    name: ‚¨£ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: üõë Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: ‚éî Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì• Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: üî¨ Lint
        run: npm run lint

  typecheck:
    needs: authorize
    name:  ¶ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: üõë Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: ‚éî Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì• Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: üîé Type check
        run: npm run typecheck --if-present

  vitest:
    needs: authorize
    name: ‚ö° Vitest
    runs-on: ubuntu-latest
    steps:
      - name: üõë Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: ‚éî Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì• Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: ‚ö° Run vitest
        run: npm run test

  playwright:
    needs: authorize
    name: üé≠ Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: üõë Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: üîë Make envfile
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          envkey_SUPABASE_ANON_PUBLIC: ${{ secrets.SUPABASE_ANON_PUBLIC }}
          envkey_SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          envkey_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          envkey_SERVER_URL: ${{ secrets.SERVER_URL }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_DIRECT_URL: ${{ secrets.DIRECT_URL }}
          envkey_SMTP_PWD: ${{ secrets.SMTP_PWD }}
          envkey_SMTP_HOST: ${{ secrets.SMTP_HOST }}
          envkey_SMTP_USER: ${{ secrets.SMTP_USER }}
          envkey_ENABLE_PREMIUM_FEATURES: ${{ secrets.ENABLE_PREMIUM_FEATURES }}
          envkey_SEND_ONBOARDING_EMAIL: ${{ secrets.SEND_ONBOARDING_EMAIL }}
          file_name: .env

      - name: ‚éî Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì• Download deps
        uses: bahmutov/npm-install@v1

      - name: üì• Install Playwright Browsers
        run: npm run test:e2e:install

      - name: ‚öôÔ∏è Build
        run: npm run build

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
